### ISSUE TITLE
Issue with exported catalog to Playfab + a couple of questions

### ISSUE THREAD

**Issue by Whiskah** [insthync/dot-io-playfab-client#3]
So I'm getting InvalidItemProperties when uploading my first catalog json file to Playfab, (After exporting from the "Playfab Monetization Exporter") 

Now as I have several game heads that arent set would this be breaking the json file? or is it as simple as all fields MUST be completed on anything that is set within a data file? (Image attached, image also relates to next question)

![Capture](https://user-images.githubusercontent.com/27635588/124997001-d2db1000-e041-11eb-96f3-9b6fa1f725f5.PNG)

Next question is, in the picture attached there is a price and prices which both seem like they must be set in order for it to work? and am I to assume that both ID's for them must match etc? 

Last question, how do these relate to the current ingame currency which was "GOLD"? If I export the currency the json shows GOLD as the current one etc so does the above value for price mean the price in GOLD etc? (I've attached both jsons as text files (as it wont let me upload jsons here) just so you can see what I'm looking at)  

[CATALOG.txt](https://github.com/insthync/dot-io-playfab-client/files/6787616/CATALOG.txt)
[CURRENCIES.txt](https://github.com/insthync/dot-io-playfab-client/files/6787617/CURRENCIES.txt)

Sorry for all the questions!

**Comment by insthync** [comment]
- It must be able to import without heads items
- `Price` is part of `Prices`, if you plan to make it only have one price option, for example, ITEM_A can be bought by GOLD only, then you don't have to set `Prices`, just set only `Price` which `Id` is `GOLD` and `Amount` as you wish. And as I see in your `CURRENCIES` file, you only have one currecy which is `GG`, so you have to use `GG` as `Id` not `2`, don't know why you put that `2`?
- I don't understand your last question.

**Comment by Whiskah** [comment]
Aha so the ID must match the currency id! I wasn't sure how those matched but that answer the other question gotcha! :)

I'm having a little trouble getting google to play nicely and allow me to login with this, must we always have to use google play games or can we just login to google etc as I don't want any functionality from their services only the ability to login with google then save/load purchases etc

**Comment by insthync** [comment]
Don't have to use Google Play games service to login. You can use other methods to login, In-App purchase history will be recorded in Playfab's dashboard

**Comment by Whiskah** [comment]
Awesome, well I've just tried to use google play games but after entering my email and password it takes me to this screen, as I can't run google play games on PC do you have any idea what is trying to load and failing here?
![image](https://user-images.githubusercontent.com/27635588/125170285-2a928c00-e1a6-11eb-858c-3e6dd6ec1130.png)

If I click outside of this box it will again ask me to choose a email account (which then brings me back to the above etc)

Edit: ok so this box was the confirm screen which wouldn't show because you needed your email to be setup as a testing user. But now I've hit this, after confirming that box I get "Authentication Canceled" any idea for this one?
![Screenshot_20210711-090855](https://user-images.githubusercontent.com/27635588/125187462-b0a2e700-e227-11eb-92e9-4353b1182ef1.jpg)

**Comment by Whiskah** [comment]
To note on this I've ran through the exact same setup needed from the SmokeTest:
https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/samples/SmokeTest
googleplay sample and this works as intended so this definitely is a problem related to this project.

**Comment by Whiskah** [comment]
Think I've fixed this so closing.
