### ISSUE TITLE
Playfab integration<Solved>

### ISSUE THREAD

**Issue by Safewaygames** [insthync/dot-io-playfab-client#6]
Hello, I am using shooter IO pun with the playfab integration the google play login and facebook login do not work anymore as the code is out of date and GPGS does not use the same methods.

The serious problem is when you purchase an item using currency that Item does not get updated and does not appear Unless you purchase another item. Also if you log out or leave game everything you have purchased will disappear but will show back up when you buy something. Can you please look into these issues.

**Comment by insthync** [comment]
I will check it.

**Comment by Safewaygames** [comment]
Thank you for looking into it its really giving me problems

**Comment by insthync** [comment]
Updated, now it logins should work

**Comment by Safewaygames** [comment]
Thank you but what about the problems with pulling the items from server was that also fixed.

**Comment by insthync** [comment]
Try add these codes
```

        var uis = FindObjectsOfType<UIProductList>(true);
        foreach (var ui in uis)
        {
            ui.onPurchaseSuccess.RemoveListener(UpdateAvailableItems);
            ui.onPurchaseSuccess.AddListener(UpdateAvailableItems);
        }
```
to Start function in `UIMainMenu` class

**Comment by Safewaygames** [comment]
I added that code to the Start function and Items bought are still not being pulled from playfab server if I buy something else everything updates but again when I log out or close game everything still disappears. and I checked playfab inventory and all purchased items are there like characters and weapons just not showing up on players end.

**Comment by Safewaygames** [comment]
https://youtu.be/eveakjLsERQ

**Comment by Safewaygames** [comment]
Also please note google play login just says login cancelled when trying to use it. download directly from google play store using internal testing FB login just crashes the app

**Comment by insthync** [comment]
May I try by using AnyDesk?

**Comment by Safewaygames** [comment]
AnyDesk the remote desktop client?

**Comment by insthync** [comment]
Yes, you can send your info to my email: ittipon.bay@gmail.com

**Comment by Safewaygames** [comment]
should be sent to your email my email is support@safewaygames.com

**Comment by insthync** [comment]
Didn't receive yet.

**Comment by Safewaygames** [comment]
Sent again using second email safwaygamesceo@gmail.com

**Comment by Safewaygames** [comment]
Also Is it possible to have more the 1 match making scene seems like matching making only works with scene and gameplay rule set in GameNetworkManager unless I’m mistaking. And thank you for all the help.

**Comment by insthync** [comment]
Not sure how are you going to use it?

**Comment by Safewaygames** [comment]
NVM
I figured it out there is a command to set method with on button click you can change gameplay before starting matchmaking

**Comment by Safewaygames** [comment]
So I figured out you can change gameplay rule so but is How can a make it so it choose a random Map instead of same scene for example
![save1](https://user-images.githubusercontent.com/71611113/177088822-0c0f3d7f-cb0d-4ef4-9f64-cf7b8d6ba019.png)
Instead of just having the one Online scene  maybe set it as an array where it can choose a random map from the list

**Comment by Vauxvogh** [comment]
Hey message me I know how to fix that and what you're looking for brother

**Comment by Safewaygames** [comment]
If you have the same name on discord I sent you a message
