### ISSUE TITLE
Match Rewards Not Being Updated

### ISSUE THREAD

**Issue by Safewaygames** [insthync/dot-io-playfab-client#8]
When using Playfab integration now when you finish a match the match rewards are not giving out and its not being updated for how much gold the player has won from last match. if you take out playfab everything works as intended.

**Comment by Safewaygames** [comment]
If you could look into this would be great

**Comment by Safewaygames** [comment]
If anyone is using the playfab integrations for shooter IO or Battle IO  and are not getting currency not being updated after battles if you login to your playfab account click on your game click on the cog next to your game name click title settings then under API Features make sure allow client to add virtual currency is checked. Save and everything should work. this might not be a permeant fix because this will also allow players to cheat in your game to add virtual currency you have set maybe we can get an update to this so it can just pull from playfab and not rely on client.

**Comment by insthync** [comment]
It is intended to work like that.

**Comment by Safewaygames** [comment]
Ok thank you for this information very much apricated.
